"""fix

Revision ID: 4bf1a00cfc0f
Revises: c367146a0244
Create Date: 2025-12-20 23:04:19.462134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf1a00cfc0f'
down_revision = 'c367146a0244'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###






